version = 0.1

[default.deploy.parameters]
stack_name = "yjp-nestjs-stack"
resolve_s3 = true
s3_prefix = "yjp-nestjs"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = [
  "DatabaseUrl=\"postgresql://postgres:yjp105009@database-aws-yjp.cluster-c9c6k0iaqvbr.us-west-2.rds.amazonaws.com:5432/postgres?schema=public\""
]
